/*
 * octos-ffi C API.
 *
 * OWNERSHIP & SAFETY CONTRACT:
 *  - An OctosRuntime* is NOT thread-safe. Serialize all calls on a handle.
 *    Never use a handle after octos_runtime_free(); never free it twice or
 *    concurrently with any other call on the same handle. Free it from a plain
 *    (non-async) thread.
 *  - Strings returned by octos_run_task()/octos_embed()/octos_memory_*()/
 *    octos_embedding_model_*() or octos_take_last_partial_result() are owned by YOU and
 *    must be freed, UNMODIFIED, with octos_string_free() -- never free(3),
 *    never twice, and do not alter the bytes or NUL terminator before freeing.
 *  - const char* from octos_last_error()/octos_version() must NOT be freed.
 *    octos_last_error() is thread-local and valid only until the next FFI call
 *    on the same thread.
 */

#ifndef OCTOS_FFI_H
#define OCTOS_FFI_H

#pragma once

/* Generated by cbindgen. DO NOT EDIT. Regenerate with the command in crates/octos-ffi/cbindgen.toml. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque runtime handle.
//
// # Thread-safety & lifetime (C-ABI contract)
//
// An `OctosRuntime` handle is NOT thread-safe. Do not call any function on a
// handle after [`octos_runtime_free`]. Do not call [`octos_runtime_free`]
// concurrently with — or while any other call on the same handle is in flight.
// Serialize all calls on a given handle (or guard it with your own mutex): a
// concurrent run+free is a use-after-free and free+free is a double-free, and
// the library cannot prevent either across a C ABI. Also free the handle from
// a plain (non-async) thread — dropping the held tokio runtime from inside
// another async/tokio context fails.
//
// (Internally: shared tokio runtime + provider + memory; a fresh [`Agent`] is
// built per task so a per-task `max_iterations` can be honored.)
typedef struct OctosRuntime OctosRuntime;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Create a runtime from a JSON config. Returns NULL on error (see
// [`octos_last_error`]); the returned handle must be freed with
// [`octos_runtime_free`].
OctosRuntime *octos_runtime_new(const char *config_json);

// Free a runtime created by [`octos_runtime_new`]. NULL is a no-op.
//
// Call from a plain (non-async) thread and never concurrently with another
// call on the same handle (see [`OctosRuntime`]).
void octos_runtime_free(OctosRuntime *runtime);

// Run a one-shot task. `brief_json` is `{"prompt": "...", "max_iterations"?:
// N}`. Returns owned JSON `{"output", "iterations", "tokens"}` that the caller
// must free, UNMODIFIED, with [`octos_string_free`] — or NULL on error.
// On an incomplete response, NULL still means failure; retrieve the partial
// output separately with [`octos_take_last_partial_result`] on this thread.
char *octos_run_task(OctosRuntime *runtime, const char *brief_json);

// Embed `text`. Returns owned JSON `{"embedding": [f32, ...]}` that the caller
// must free, UNMODIFIED, with [`octos_string_free`] — or NULL on error.
// Requires the `embed-llama` feature and a loaded model: the config's
// `embedding_model_path`, or the default model resolved at
// [`octos_runtime_new`] (see [`octos_embedding_model_ensure`]). Without one
// the last error is "no embedder configured".
char *octos_embed(OctosRuntime *runtime, const char *text);

// Report what is on disk for the default embedding model (EmbeddingGemma-300M
// Q8_0) under `data_dir` — the same directory a runtime's `data_dir` config
// names. Needs NO runtime handle and never touches the network. Returns owned
// JSON `{"path", "present", "bytes", "complete", "url", "license_url",
// "sha256"}` that the caller must free, UNMODIFIED, with [`octos_string_free`]
// — or NULL on error. `complete` means present at the pinned size (a partial
// download is `present` but not `complete`); `url` is the public release the
// file is fetched from and `license_url` the terms that apply to the weights
// (Gemma Terms of Use).
char *octos_embedding_model_status(const char *data_dir);

// Make sure the default embedding model is complete under `data_dir`,
// downloading and SHA-256-verifying it (334 MB, once) when `download` is
// true. Needs NO runtime handle, so a host can provision the model — on its
// own schedule, from a plain thread — BEFORE [`octos_runtime_new`], which
// otherwise blocks on the same download when `embedding_auto_download` is
// not `false`. Returns owned JSON `{"path"}` that the caller must free,
// UNMODIFIED, with [`octos_string_free`] — or NULL on error: the file is
// absent and `download` is false (or `OCTOS_NO_MODEL_DOWNLOAD` is set in the
// environment, which vetoes even an explicit `true`), or the download failed
// or did not verify (the partial file is discarded).
char *octos_embedding_model_ensure(const char *data_dir, bool download);

// Push app records into the Recall memory index. `request_json` is
// `{"records": [Record…], "vectors"?: [[f32…]|null…], "embed"?: bool}` where a
// Record is `{"id", "kind": "document"|"episode", "source", "timestamp":
// RFC3339, "title", "abstract", "parent"?, "body"?, "fingerprint"?}`. At most
// 500 records per call; `kind: "knowledge"` is rejected; `trust` is forced to
// untrusted. Without `vectors`, records are embedded here when an embedder is
// loaded (else indexed BM25-only). Returns owned JSON `{"inserted",
// "updated", "unchanged", "vectors_stored", "embedded"}` that the caller must
// free, UNMODIFIED, with [`octos_string_free`] — or NULL on error.
char *octos_memory_upsert(OctosRuntime *runtime, const char *request_json);

// Search the Recall memory index. `request_json` is `{"query": "...",
// "kinds"?: [..], "sources"?: [..], "since"?: RFC3339|YYYY-MM-DD, "until"?:
// RFC3339|YYYY-MM-DD, "limit"?: N}`. Returns owned JSON `{"hits": [{"id",
// "kind", "source", "title", "abstract", "score", "timestamp", "trust"}…]}`
// that the caller must free, UNMODIFIED, with [`octos_string_free`] — or NULL
// on error. The query is embedded when an embedder is loaded; BM25 otherwise.
char *octos_memory_search(OctosRuntime *runtime, const char *request_json);

// Load one Recall record by `id`, counting the visit. Returns owned JSON
// `{"record": Record}` that the caller must free, UNMODIFIED, with
// [`octos_string_free`] — or NULL on error (last error "no such record" when
// the id is unknown).
char *octos_memory_load(OctosRuntime *runtime, const char *id);

// Recall index statistics. Returns owned JSON `{"records", "vectors_stored",
// "vectors_resident", "by_kind", "by_source", "dimension", "embedder_id",
// "graph_persisted", "disk_bytes"}` that the caller must free, UNMODIFIED,
// with [`octos_string_free`] — or NULL on error.
char *octos_memory_stats(OctosRuntime *runtime);

// Free a string returned by [`octos_run_task`], [`octos_embed`], an
// `octos_memory_*` or `octos_embedding_model_*` function, or
// [`octos_take_last_partial_result`]. NULL is a no-op.
//
// The string is owned by the caller and MUST be freed here, UNMODIFIED — do
// not alter its bytes or NUL terminator before freeing. (This reclaims via
// `CString::from_raw`, which rescans for the NUL; a mutated terminator
// miscomputes the length and corrupts the allocator.) Never call `free(3)` on
// these; never double-free.
void octos_string_free(char *s);

// Return the thread-local last-error string, or NULL if none. Do NOT free it;
// valid only until the next FFI call on this thread.
const char *octos_last_error(void);

// Take this thread's last incomplete task result as owned JSON with the same
// shape as [`octos_run_task`]. Returns NULL if absent or already taken. This
// does not change the error diagnostic and does NOT turn the task into success.
//
// Consume once on the SAME thread, before another `octos_runtime_new`,
// `octos_run_task`, `octos_embed`, `octos_memory_*` or
// `octos_embedding_model_*` call (success or failure clears it).
// Any new error, including a caught panic, also clears it. Error/version
// inspection and successful free calls leave it available. The caller must
// free the returned allocation, UNMODIFIED, with [`octos_string_free`].
// The payload is lossless model output, not a sanitized/600-byte diagnostic.
char *octos_take_last_partial_result(void);

// Return the crate version as a static NUL-terminated string (never freed).
const char *octos_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OCTOS_FFI_H */
